const ActionTypes={
    LIST_LOADING:"LIST_LOADING",
    LIST_ERROR:"LIST_ERROR",
    LIST_SUCCES:"LIST_SUCCES",
    ADD_TO_LIST:"ADD_TO_LIST",
    REMOVE_FROM_LIST:"REMOVE_FROM_LIST",
}
export default ActionTypes